### ISSUE TITLE
Eclipse compile issues

### ISSUE THREAD

**Issue by stuntguy3000** [Wurst-Imperium/Wurst-MC-1.10#74]
After following all the steps, I am having this runtime error:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:87)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at net.minecraft.client.Minecraft.getSystemTime(Minecraft.java:3203)
	at net.minecraft.client.main.Main.main(Main.java:43)
	at Start.main(Start.java:11)
```

I notice there is no information on how to actually **compile and run** the project, so that might be where i'm going wrong.

**Comment by GlitchHead** [comment]
In MCP goto C:\Users\Steven\Downloads\mcp935-rc1\jars\versions\1.11 and copy the folder called "1.11-natives" to your lib folder in eclipse then attach the source folder natives to your libraries.

**Comment by stuntguy3000** [comment]
Got it working now, cheers.
